[package]
name = "vulkan-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.31.0"
glfw = { version = "0.50.0", features = ["vulkan"] }

[profile.dev]
opt-level = 1
